version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=education_db
      - DB_USER=artursettarov
      - DB_PASSWORD=SAcoder0228
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=education_db
      - DB_USER=artursettarov
      - DB_PASSWORD=SAcoder0228
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0


volumes:
  postgres_data:
