# Generated by Django 6.0.6 on 2026-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='telegram_id',
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
