# Generated by Django 6.0.6 on 2026-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parents_telegram_id_alter_parents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
